# Generated by Django 5.1.1 on 2024-09-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerental.customer'),
        ),
    ]
